export const shopcategories = [
    { value: "fashion", label: "Fashion" },
    { value: "mens_clothing", label: "Men's Clothing" },
    { value: "womens_clothing", label: "Women's Clothing" },
    { value: "kids_clothing", label: "Kids Clothing" },
    { value: "footwear", label: "Footwear" },
    { value: "bags_luggage", label: "Bags & Luggage" },
    { value: "jewelry", label: "Jewelry" },
    { value: "watches", label: "Watches" },
    { value: "eyewear", label: "Eyewear" },
    { value: "accessories", label: "Accessories" },

    { value: "beauty_personal_care", label: "Beauty & Personal Care" },
    { value: "cosmetics", label: "Cosmetics" },
    { value: "skincare", label: "Skincare" },
    { value: "haircare", label: "Haircare" },
    { value: "fragrances", label: "Fragrances" },
    { value: "health_wellness", label: "Health & Wellness" },
    { value: "pharmacy", label: "Pharmacy" },

    { value: "electronics", label: "Electronics" },
    { value: "mobile_phones", label: "Mobile Phones" },
    { value: "computers", label: "Computers & Laptops" },
    { value: "accessories_electronics", label: "Electronics Accessories" },
    { value: "gaming", label: "Gaming" },
    { value: "cameras", label: "Cameras" },
    { value: "audio", label: "Audio & Headphones" },
    { value: "home_appliances", label: "Home Appliances" },

    { value: "home_living", label: "Home & Living" },
    { value: "furniture", label: "Furniture" },
    { value: "home_decor", label: "Home Decor" },
    { value: "kitchen_dining", label: "Kitchen & Dining" },
    { value: "bedding", label: "Bedding" },
    { value: "lighting", label: "Lighting" },
    { value: "garden_outdoor", label: "Garden & Outdoor" },

    { value: "food_grocery", label: "Food & Grocery" },
    { value: "beverages", label: "Beverages" },
    { value: "snacks", label: "Snacks" },
    { value: "organic", label: "Organic Products" },
    { value: "restaurant", label: "Restaurant" },
    { value: "bakery", label: "Bakery" },

    { value: "sports_fitness", label: "Sports & Fitness" },
    { value: "gym_equipment", label: "Gym Equipment" },
    { value: "outdoor_sports", label: "Outdoor Sports" },
    { value: "cycling", label: "Cycling" },

    { value: "toys_games", label: "Toys & Games" },
    { value: "baby_products", label: "Baby Products" },
    { value: "books_stationery", label: "Books & Stationery" },
    { value: "office_supplies", label: "Office Supplies" },
    { value: "art_crafts", label: "Art & Crafts" },

    { value: "automotive", label: "Automotive" },
    { value: "motorcycles", label: "Motorcycles" },
    { value: "car_accessories", label: "Car Accessories" },

    { value: "pets", label: "Pet Supplies" },
    { value: "services", label: "Services" },
    { value: "digital_products", label: "Digital Products" },
    { value: "gift_flowers", label: "Gifts & Flowers" },
    { value: "handmade", label: "Handmade Products" },
    { value: "second_hand", label: "Second Hand" },
    { value: "other", label: "Other" }
];